[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
p2a = "9uWnELB4ExQ4HY4YhSPb6pkGchaLCzty1BryX8w5xqVu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
