version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ~/.config/solana:/root/.config/solana
    restart: unless-stopped 